title: OrderOnline Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://oo-status.netlify.com'
params:
  alwaysKeepBrandColor: true
  autoRefresh: true
  brand: ffffff
  dateFormat: '2 January, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: cc4400
  down: e60000
  googleAnalytics: UA-00000000-1
  incidentPostsPerPage: 10
  logo: /img/orderonline.png
  notice: 24478f
  ok: 8dc63f
  shortDateFormat: '15:04 — 2 Jan'
  systems:
    - description: Where users login and manage their products and orders
      name: APP
    - description: The guts of the application.
      name: API
    - description: >-
        This is the service responsible for serving js, images, audio, and
        video. Using AWS CloudFront
      name: CDN
    - description: ''
      name: Checkout Pages
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
